import type { Metadata } from "next";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import DockWrapper from "@/components/ui/dock/DockWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Campus Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} bg-shell-200 ${geistMono.variable} antialiased`}
        >
          <Navbar className="md:hidden" />
          {children}
          <Toaster />
          <DockWrapper />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
